$schema: https://golangci-lint.run/schemas/v2.json
version: "2"
run:
  tests: true

tools:
  - id: bidichk
    enabled: true
  - id: bodyclose
    enabled: true
  - id: durationcheck
    enabled: true
  - id: errchkjson
    enabled: true
  - id: errname
    enabled: true
  - id: errorlint
    enabled: true
  - id: exhaustive
    enabled: true
  - id: goconst
    enabled: true
    settings:
      min-len: 3
      min-occurrences: 6
  - id: gosec
    enabled: true
  - id: importas
    enabled: true
  - id: makezero
    enabled: true
  - id: misspell
    enabled: true
  - id: revive
    enabled: true
  - id: sqlclosecheck
    enabled: true
  - id: staticcheck
    enabled: true
  - id: unconvert
    enabled: true
  - id: whitespace
    enabled: true
  - id: gofmt
    enabled: true
    settings:
      simplify: true
  - id: goimports
    enabled: true

filters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  severity:
    default: error
    overrides:
      - linters: [dupl]
        severity: info
