# This is a configuration file for yamllint, a linter for YAML files.
# For more information, see
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default
rules:
  document-start: disable
  line-length: disable
  quoted-strings: disable
  octal-values:
    forbid-implicit-octal: true
  truthy: disable
