version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - confluentinc
  - cyclop
  - gofumpt
  - golines
  - swaggo
    - GOROOT
  - Reymers
  - arangodb
  - arangolint
  - asciicheck
  - asasalint
  - canonicalheader
  - containedctx
  - contextcheck
  - copyloopvar
  - decorder
  - depguard
  - dupword
  - embeddedstructfieldcheck
  - exhaustruct
  - exptostd
  - fatcontext
  - forcetypeassert
  - forbidigo
  - funcorder
  - funlen
  - gocheckcompilerdirectives
  - gochecknoinits
  - gochecknoglobals
  - gochecksumtype
  - gocognit
  - gocritic
  - gocyclo
  - godox
  - gofrs
  - goheader
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosmopolitan
  - gostd
  - iface
  - inamedparam
  - iface
  - interfacebloat
  - intrange
  - ireturn
  - kitlog
  - klog
  - loggercheck
  - logl
  - maintidx
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilness
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - noinlineerr
  - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - perfsprint
  - prealloc
  - predeclared
  - predeclared
  - promlint
  - promlinter
  - protogetter
  - recvcheck
  - rowserrcheck
  - sarama
  - sloglint
  - spancheck
  - sprintf
  - structname
  - tagalign
  - testableexamples
  - testifylint
  - testpackage
  - thelper
  - tparallel
  - unparam
  - usestdlibvars
  - usetesting
  - varnamelen
  - wastedassign
  - wrapcheck
  - zerologlint
  - Axxxx
  - GOROOT
  - golint
  - ginkgolinter
  - gomega
  - gopkg
  - jmoiron
  - logr
  - mapstructure
  - mitchellh
  - nlreturn
  - strconv
  - strconcat
  - swaggo
  - testcontainers
  - underef
  - fieldalignment
ignoreWords: []
import: []
