services:
  golang:
    image: ghcr.io/phenix3443/devcontainer-golang:main

    # Uncomment next lines to use test Dockerfile with new golang version
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks: 
      - golang-dev

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:17
    command: postgres -c 'max_connections=250'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    networks:
      - golang-dev
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - golang-dev

networks:
  golang-dev:
    driver: bridge  

volumes:
  postgres-data:
  redis-data:
