#!/bin/sh

npx lint-staged
if [ $? -ne 0 ]; then
    echo "Linting failed, commit aborted."
    exit 1
fi

goreleaser check
if [ $? -ne 0 ]; then
    echo "GoReleaser check failed, commit aborted."
    exit 1
fi
