name: Sync Template Repo

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Upstream Repo
        run: |
          git remote add upstream https://github.com/phenix3443/go-starter.git
          git fetch upstream

      - name: Merge Changes
        run: |
          git checkout main
          git merge upstream/main || echo "No changes to merge"

      - name: Push Changes
        run: |
          git push origin main || echo "No new changes to push"