name: Unittest with Coverage

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**/*.go"
  push:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  code_coverage:
    name: Code coverage report
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: unit_tests
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@v1.1.1
        with:
          coverage-artifact-name: code-coverage
          coverage-file-name: coverage.txt
